spring.application.name=task-management-system

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/task_management}
spring.datasource.username=${DB_USERNAME:task_app}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
