CREATE TABLE accounts
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id),
    CONSTRAINT uk_accounts_email UNIQUE (email)
);

CREATE TABLE tasks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    author_id   BIGINT       NOT NULL,
    assignee_id BIGINT,
    CONSTRAINT pk_tasks PRIMARY KEY (id),
    CONSTRAINT ck_tasks_status CHECK (status IN ('CREATED', 'IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT fk_tasks_author FOREIGN KEY (author_id) REFERENCES accounts (id),
    CONSTRAINT fk_tasks_assignee FOREIGN KEY (assignee_id) REFERENCES accounts (id)
);

CREATE TABLE comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text      VARCHAR(255) NOT NULL,
    task_id   BIGINT       NOT NULL,
    author_id BIGINT       NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_task FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES accounts (id)
);
